pipeline {
   agent any

   stages {
      stage('pull code') {
         steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, 
            extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '7e80aee3-8986-4c7e-a549-9da51f7dac37', url: 'git@github.com:Ren1336621051/2020FSD_Milestone5_backend.git']]])
         }
      }
      stage('build project') {
         steps {
            sh 'mvn clean install'
         }
      }
      stage('publish project') {
         steps {
            deploy adapters: [tomcat8(credentialsId: '3a8c0307-29e5-44d0-9e5b-9280a6bcfd2d', path: '', url: 'http://192.168.66.102:8080')], contextPath: null, war: 'target/*.war'
         }
      }
   }
}
